services:
  fastapi:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "3030:3030"  # Map container port 8000 to host port 8000
    volumes:
      - ./backend/app:/app  # Mount local app directory to container (for development)

  vue:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map container port 80 to host port 80
    depends_on:
      - fastapi  # Ensure FastAPI service starts before Vue
